### ISSUE TITLE
Show Translucent Status Bar

### ISSUE THREAD

**Issue by IanPozz** [Over17/UnityShowAndroidStatusBar#1]
Hi, I've just started looking to use this plug-in but when it shows the status bar it's always black, opaque and it pushes the content of my App down and off the screen. Is it possible to change the status bar so it's overlaid on top of my App content and in a translucent style?

Many thanks
Ian

**Comment by Over17** [comment]
Hey @IanPozz !

Please check the latest commit (works on KitKat+).
It's also easy to switch between transparent and non-transparent status bar - one-word-change in the manifest. I'll add more info into the readme.

Of course, your UI should be designed with the status bar in mind :)

I'll close the issue when I check everything on several phones.

**Comment by Over17** [comment]
Checked on a range of phones - seems to work fine: Nexus 6, Galaxy S6, Galaxy Nexus, Galaxy S.

**Comment by Over17** [comment]
Added, readme updated.
