### ISSUE TITLE
How to integrate into existing Android studio project that contains Unity module?

### ISSUE THREAD

**Issue by wilk3ns** [Over17/UnityShowAndroidStatusBar#10]
Hi! Awesome project! Managed to work inside my Unity app. Deployed worked perfectly. But I want to ask is there possibility that I can implement this on my existing Android studio project that includes Unity module. After setting Fullscreen false in Unity, Toolbar and navigation bar appeared but statusbar still not visible.
 Thank you very much!

**Comment by Over17** [comment]
Hi! Sorry for missing your issue!

You will probably need to integrate the code from this plugin into your Android Studio project. Important parts are:
- manifest (activity name and theme)
- the activity code, includes the flag clearing and OnSystemUiVisibilityChangeListener
