### ISSUE TITLE
Using this plugin alongside Firebase Cloud Messaging

### ISSUE THREAD

**Issue by BielBG** [Over17/UnityShowAndroidStatusBar#12]
Hi, we want to implement the Firebase Cloud Messaging on our app, which already has this plugin. In order to make this plugin work, we have a our main activity the "com.unity3d.nostatusbar.UnityPlayerActivityStatusBar", which we found in your /src files (here: https://github.com/Over17/UnityShowAndroidStatusBar/blob/master/src/UnityShowAndroidStatusBar/src/main/java/com/unity3d/nostatusbar/UnityPlayerActivityStatusBar.java), extends from UnityPlayerActivity. Well, Firebase says this: "If your custom activity extends UnityPlayerActivity you can instead extend com.google.firebase.MessagingUnityPlayerActivity which implements all necessary methods.". Which, apparently, is the case, but how can we do it where this class extends from UnityPlayerActivity, make it extend from MessagingUnityPlayerActivity instead? Because all the package contains is an Android Manifest and an aar file, and we can't modify that .aar file (which we suppose contains that script, encrypted or whatnot).

Help pls!

**Comment by Over17** [comment]
Hi!

The source code of the aar is here: https://github.com/Over17/UnityShowAndroidStatusBar/tree/master/src/UnityShowAndroidStatusBar

The build instructions are in the main readme file, "How to Build" section.

You may want to:
- add firebase as a compile-time dependency
- update https://github.com/Over17/UnityShowAndroidStatusBar/blob/master/src/UnityShowAndroidStatusBar/src/main/java/com/unity3d/nostatusbar/UnityPlayerActivityStatusBar.java to inherit from needed class
- build as described in the readme
- use the resulting aar.

No warranty it will work though! Can't find the code of the firebase activity at a glance.

Hope that helps.

**Comment by BielBG** [comment]
Hi again, Yury. We tried to do that, but an error occurs when we run gradlew assemble.

ERROR: 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'UnityShowAndroidStatusBar'.
> Failed to notify project evaluation listener.
   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
   > Could not get unknown property 'generateReleaseBuildConfig' for root project 'UnityShowAndroidStatusBar' of type org.gradle.api.Project.

We added a local.properties file with the sdk location in it (sdk.dir=C:/Users/biley/AppData/Local/Android/sdk), and tried gradlew assemble again, with another error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'UnityShowAndroidStatusBar'.
> Failed to notify project evaluation listener.
   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
   > Could not get unknown property 'generateReleaseBuildConfig' for root project 'UnityShowAndroidStatusBar' of type org.gradle.api.Project.

At this point we don't know what to do, and we need this to work, we need the UnityPlayerActivityStatusBar to extend from MessagingUnityPlayerActivity.

**Comment by BielBG** [comment]
My bad, the second error shows this (I copied the same error 2 times :/)

> Failed to notify project evaluation listener.
   > javax/xml/bind/annotation/XmlSchema
   > Could not get unknown property 'generateReleaseBuildConfig' for root project 'UnityShowAndroidStatusBar' of type org.gradle.api.Project.

**Comment by BielBG** [comment]
Nevermind, I finally solved everything. There were more than 1 JDK installed on the PC, that caused the error. Also had duplicated Android SDK 'Tools' folder duplicated (the 'old' ones) because to build Android projects on Unity, you have to had an specific Tools version.

Ah, and I got kinda confused in the "How to build" sections, because it says "UnityAndroidPermissions", which is another plugin of yours, you might want to change that :P 

Just one last question: I got 2 .aar, the debug and release, is it possible to only have 1? Without the -debug or -release tags? Thank you!

**Comment by Over17** [comment]
Glad to hear you solved the issue.

> because to build Android projects on Unity, you have to had an specific Tools version.
That's not true. Unless you are using a very old patch release and/or wrong JDK, latest tools work flawlessly! https://forum.unity.com/threads/java-9-jdk-9-support-by-unity-android.499354/page-2#post-3537964

I'll fix the docs! Thanks for the heads up

Re 2 aars - use the release one (this is what I do). Alternatively, you can do gradlew assembleRelease - it will produce only the release aar.

**Comment by Over17** [comment]
README fixed.

**Comment by SupranJowti** [comment]
how cam i use MessagingUnityPlayerActivity?
