### ISSUE TITLE
Status bar not visible on Galaxy S8+

### ISSUE THREAD

**Issue by ataylor09** [Over17/UnityShowAndroidStatusBar#14]
Hi there, thanks for making the plugin.

I cannot get this work correctly on my Galaxy S8+ device (running Android 8.0.0). 

Unity version: 2018.0.0f2. 

OS: Windows 10

I have included the AndroidManifest and the AAR files in:

Assets/Plugins/Android/

In the Start method of one of my scripts I have set Screen.fullScreen = false;

Behavior on my device is that the status bar is only visible when you swipe from the bottom of the screen or the top of the screen.

**Comment by Over17** [comment]
There was a bug in Unity when fullScreen = false didn't work.

Your Unity version seems to be incorrect; I expect it to be 18.1, in that case please update to the latest patch release or to 18.2.
