### ISSUE TITLE
how to change color of the gray statusbar

### ISSUE THREAD

**Issue by vahidreza** [Over17/UnityShowAndroidStatusBar#15]
hey
I tried below code and put it inside the  `@Override protected void onStart()` method in the UnityPlayerActivity.java file with no success. 

`  if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
            getWindow().setStatusBarColor(Color.parseColor("#FAFAFA"));
        }`

Is there anyway so I can change the statusbar color even for sdk versions before lolipop?

**Comment by Over17** [comment]
You can try AppCompat library: https://chris.banes.me/2014/10/17/appcompat-v21/
