### ISSUE TITLE
How to prevent 'swipe down from the top to exit full screen' bubble on device

### ISSUE THREAD

**Issue by xiongyijun** [Over17/UnityShowAndroidStatusBar#16]
On Android TV(4.4) , using Unity 2018.2 , every time my game starts up I get this bubble issued by Android:
"swipe down from the top to exit full screen".

How to prevent it, or disable IMMERSIVE.

I had used "fullScreen = false" in my game , but the bubble still shown in Unity splash, until first Scene loaded end.
Thank you.

**Comment by Over17** [comment]
Unfortunately it's an Android OS mechanism which shows this bubble. I'm not aware of a way to hide it. Sorry for the bad news!
