### ISSUE TITLE
Transparent Navigation Bar

### ISSUE THREAD

**Issue by SamuelKnox** [Over17/UnityShowAndroidStatusBar#17]
Using the plugin makes the bottom navigation bar transparent.  Using the opaque theme UnityStatusBarTheme makes it solid again, but then the top status bar is gray.

Device -> Pixel 2 XL running Android 8.1.0

**Comment by Over17** [comment]
What is your expected behavior?

**Comment by SamuelKnox** [comment]
It is expected that the plugin will not affect the navigation bar.  It is also expected that the opaque version of the status bar would be the same color as the opaque version of the navigation bar (black).

**Comment by Over17** [comment]
Sorry for a very late answer.

You can configure the transparency of the navigation bar on your own, by changing the flag
<item name="android:windowTranslucentNavigation">true</item>
in style definitions (values-v21 and values-v19), and then repacking/recompiling the aar.

On the opaque status bar color - it's controlled by the theme, in this case Theme.Material.Light.NoActionBar.Fullscreen. Unity by default uses Light themes, but I'd agree a dark one by default here makes more sense. I'll fix that.

**Comment by Over17** [comment]
Non-light theme used in 0.5 release.
