### ISSUE TITLE
[BUG] Issue with Huawei P20 Pro & Unity 2018.3

### ISSUE THREAD

**Issue by liszto** [Over17/UnityShowAndroidStatusBar#19]
Hello,
I have an issue with Huawei P20 Pro and Unity 2018.3 and your plugin.
On Unity 2017.4.21 with a simple script with fullscreen = false; 
I change only one thing in your value xml files. It's the ".Light" that I have removed to have a full opaque display.

I have this display on the screen : 
![screenshot_20190304_112040_com ubiant screen](https://user-images.githubusercontent.com/408031/53727432-84654780-3e70-11e9-8cff-0930e40cb2e9.jpg)

where with Unity 2018.3.4 I have this : 
![screenshot_20190304_112004_com ubiant screen](https://user-images.githubusercontent.com/408031/53727434-87f8ce80-3e70-11e9-9429-8a556fc2cedf.jpg)

My script is quite simple : 

```
using UnityEngine;
using TMPro;

public class ScreenDetection : MonoBehaviour
{
	public TextMeshProUGUI text1;
	public TextMeshProUGUI text2;

	private void Awake()
	{
		Screen.fullScreen = false;
	}

	// Start is called before the first frame update
	void Start()
    {
		text1.text = "Screen size : " + Screen.width + " // " + Screen.height;
		text2.text = "Safe size : " + Screen.safeArea.width + " // " + Screen.safeArea.height;
	}
}
```

Is it something to solve in your plugin or is it an Unity issue ?

Is there a way to detect when the device doesn't have physical input but only soft display directly on the screen to redefine the the "safescreen" area cause Android seems to get rid of this when I use the Unity variable (due probably to OS limitation)

thanks in advance @Over17 !

**Comment by MPeloquin** [comment]
We have the same issues on 2018.3

**Comment by liszto** [comment]
I found 2 possibles solutions. I can give you them @MPeloquin and submit a patch to @Over17 !

First one, is to add this to your manifest and it will manage Huawei device with a notch. 
`<meta-data android:name="android.notch_support" android:value="true"/>`

Second one is much more generic and consist to add this in the onCreate method from @Over17 java class and regenerate it with Android Studio : 
```
WindowManager.LayoutParams lp = getWindow().getAttributes();
lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER;
//Set layout extend to Notch area
getWindow().setAttributes(lp);
```

This last solution allow me to manage all devices with a notch ;) as far as I know

**Comment by liszto** [comment]
I edit my previous post cause i wrote "LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES" instead of "LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER". The NEVER force natively the activity to not use the Notch area instead of let the app managing it terribly bad. I will fix issue on the notch side and on the navigation bar side.

**Comment by elberto** [comment]
Same issue here with G6 Play on Pie.
Tried first one and second one with no luck on Unity 2018.3.11f1
if someone made it , a fork will be nice.
Thanks !

**Comment by Over17** [comment]
@liszto I tried your patch, and it didn't work for me on a Pixel 3XL.

**Comment by liszto** [comment]
@Over17 it didn't work in portrait ? Or in landscape ? 
I'm having the issue for landscape but currently I found no solution for this :/ 

I can linked my Android project if you want cause in portrait on all our devices (I didn't have a Pixel 3XL) it works.

**Comment by Over17** [comment]
Didn't work in either. The stripe is there from the very beginning in portrait.

**Comment by liszto** [comment]
I'm opening my Android Studio project. And I will drop here my entire patch (it maybe changed since my post above).
You scared me with your Pixel 3XL 😨

**Comment by Over17** [comment]
Same issue as #18 .

**Comment by liszto** [comment]
@Over17 
This is what I'm doing in my project : 
```
package com.manzalab.ubiant.plugins;

import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.view.WindowManager;

import com.unity3d.player.UnityPlayerActivity;


public class UbiantOverrideUnityActivity extends UnityPlayerActivity
{
    public static int statusBarHeight = 0;
    public static int softButtonBarHeight = 0;

    private static int getLowProfileFlag()
    {
        return View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY |
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_FULLSCREEN;
    }

    private void showSystemUi()
    {
        // Works from API level 11
        mUnityPlayer.setSystemUiVisibility(mUnityPlayer.getSystemUiVisibility() & ~getLowProfileFlag());
    }

    private void addUiVisibilityChangeListener()
    {
        mUnityPlayer.setOnSystemUiVisibilityChangeListener(new View.OnSystemUiVisibilityChangeListener()
        {
            @Override
            public void onSystemUiVisibilityChange(final int visibility)
            {
                // Whatever changes - force status/nav bar to be visible
                showSystemUi();
            }
        });
    }

    public static int statusBarHeight()
    {
        return statusBarHeight;
    }

    public static int softButtonBarHeight()
    {
        return softButtonBarHeight;
    }

    public int getStatusBarHeight()
    {
        int result = 0;
        int resourceId = getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }

    public int getSoftButtonsBarHeight()
    {
        // navigation bar height
        int navigationBarHeight = 0;
        int resourceId = getResources().getIdentifier("navigation_bar_height", "dimen", "android");
        if (resourceId > 0) {
            navigationBarHeight = getResources().getDimensionPixelSize(resourceId);
        }
        return navigationBarHeight;
    }

    /**
     * Dispose of the mUnityPlayer when restarting the app.
     * This ensures that when the app starts up again it does not start with stale data.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        if (mUnityPlayer != null)
        {
            mUnityPlayer.quit();
            mUnityPlayer = null;
        }

        statusBarHeight = getStatusBarHeight();
        softButtonBarHeight = getSoftButtonsBarHeight();

        super.onCreate(savedInstanceState);
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);

        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)
        {
            WindowManager.LayoutParams lp = getWindow().getAttributes();
            lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER;
            //Set layout extend to Notch area
            getWindow().setAttributes(lp);
        }

        // Clear low profile flags to apply non-fullscreen mode before splash screen
        showSystemUi();
        addUiVisibilityChangeListener();
    }
}
```

Based on your solution with my custom elements I didn't found one device in my company where this snippet didn't work. (Maybe on a Pixel 3XL).

It's not a solution for the landscape stuff by the way cause I still have the lanscape issue even with this.

**Comment by liszto** [comment]
I forget to link my values files from my project : 

values-14.xml : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="UnityStatusBarTheme" parent="android:Theme.Holo.Light.DarkActionBar" />
    <style name="UnityTransparentStatusBarTheme" parent="UnityStatusBarTheme" />
</resources>
```

values-19.xml : 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="UnityStatusBarTheme" parent="android:Theme.Holo.Light.DarkActionBar">
        <item name="android:windowBackground">@android:color/black</item>
    </style>
    <style name="UnityTransparentStatusBarTheme" parent="UnityStatusBarTheme">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
</resources>
```

values-21.xml : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="UnityStatusBarTheme" parent="android:Theme.Material.Light.NoActionBar.Fullscreen" >
        <item name="android:statusBarColor">@android:color/black</item>
        <item name="android:navigationBarColor">@android:color/black</item>
        <item name="android:windowBackground">@android:color/black</item>
    </style>
    <style name="UnityTransparentStatusBarTheme" parent="UnityStatusBarTheme">
        <item name="android:windowTranslucentStatus">false</item>
        <item name="android:windowTranslucentNavigation">false</item>
    </style>
</resources>
```

values.xml : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="UnityStatusBarTheme" parent="android:Theme.NoTitleBar.Fullscreen"/>
    <style name="UnityTransparentStatusBarTheme" parent="UnityStatusBarTheme"/>
</resources>
```

**Comment by Over17** [comment]
Okay I identified the change in Unity which caused this behavior - it's the Android notch support. Digging further.

**Comment by liszto** [comment]
@Over17 any news on your Unity side of this issue ?

**Comment by Over17** [comment]
Here's the link to the public issue tracker: https://issuetracker.unity3d.com/issues/android-android-9-devices-with-a-notch-are-not-in-full-screen-black-bar-is-visible-at-the-bottom-of-the-screen

**Comment by Over17** [comment]
Okay looks like I've fixed the bug in Unity. It will take some time to take it into 18.3, 19.1, 19.2 and 19.3.

**Comment by liszto** [comment]
Awesome!

**Comment by mikavaliviita** [comment]
> Okay looks like I've fixed the bug in Unity. It will take some time to take it into 18.3, 19.1, 19.2 and 19.3.

Great work! While waiting for it to appear, is there any way around this?

**Comment by elberto** [comment]
@Over17 Nice!

**Comment by Over17** [comment]
@mikavaliviita unfortunately I don't have a workaround - it's a change in native Unity code, and I can't imagine a way to apply it from outside without proper hacking.

**Comment by Over17** [comment]
The fix has landed into:
2019.3.0a2
2019.2.0a15

2019.1 and 2018.4 pending.

**Comment by Over17** [comment]
Fix landed into 2019.1.2f1.

**Comment by QuentinGprd** [comment]
> Fix landed into 2019.1.2f1.

Thank you. Is there a release date?

**Comment by Over17** [comment]
Supposedly next week.

**Comment by liszto** [comment]
I hope it will land in 2018.4 too #hope

**Comment by Over17** [comment]
Never lose hope!
Landing into 2018.4.1f1.
