### ISSUE TITLE
Prevent the android bubble saying "swipe down from the top to exit full screen"

### ISSUE THREAD

**Issue by KevinSmall** [Over17/UnityShowAndroidStatusBar#2]
I'd like to prevent that android bubble saying "swipe down from the top to exit full screen" that appears when in immersive or full screen modes. My goal is to have that bubble not appear.

I tried this plugin, and unfortunately the bubble still appears (only once though, but I want it prevented always). My game can start non-immersive and non-full screen, whatever it takes to get that bubble to not appear.  I wonder if the cause is the splash screen setting fullscreen = true.

Would it be possible to adapt this plug-in to prevent that bubble appearing? I thought the plugin was going to work, because it clears all the immersive/full screen flags.

Many thanks, Kevin.

**Comment by Over17** [comment]
Do I understand this correctly:
1. You are using the plugin to show the status bar on KitKat+ devices
2. You added `Screen.fullScreen = false;` to your scripts
3. You still see an immersive mode popup?
4. What device are you using?
Need some more details.

**Comment by Over17** [comment]
The reminder bubble is a security mechanism built into Android to prevent other apps from "mimicking" the system interface, and you can't disable it on a standard Android. There are options to get rid of it on custom ROMs though.

More details:
http://android.stackexchange.com/questions/113333/is-there-a-way-to-block-the-immersive-mode-prompt-swipe-down-from-the-top-to-ex
http://stackoverflow.com/questions/20075041/immersive-mode-instructions-reappear-every-time-the-device-enters-this-mode

**Comment by KevinSmall** [comment]
1. You are using the plugin to show the status bar on KitKat+ devices
> Yes (although this behaviour happens both with and without the plugin there)
2. You added Screen.fullScreen = false; to your scripts
> Yes
3. You still see an immersive mode popup?
> Yes, but only once the first time the app is ever run.  If the popup is dismissed just once by pressing OK then it never appears again, even if device powered off/on.  It takes an uninstall of the app to cause it to appear again.
I am wondering, is it the Unity Splash Screen that is sending a "full screen = true" and triggering the OS to issue the message. If I buy a license for Plus, and disable the splash screen entirely, and just have "full screen = false" in my script, might that make the message go away?
4. What device are you using?
> I am testing on an Android Virtual Device via Visual Studio, a Nexus 5 Android 4.4.2 API 19.

**Comment by KevinSmall** [comment]
And thanks for explanation as to why Android OS issues the message, it makes sense.

I suppose my question can be worded a different way also - how can I deploy a Unity Android application that does NOT go into immersive/full-screen mode, even for a single frame.

I want my app to be non-full screen non-immersive always and not cause that message to be triggered by the OS, even once.

Many thanks for looking into this, Yuri, it is really appreciated.

**Comment by Over17** [comment]
@KevinSmall just to be sure - what's the Unity version you are using?

This is true that IMMERSIVE flag is set on startup by Unity, so until the Start() method in the script is executed, it stays immersive.

However, when testing, I never saw this bubble notification on any device - maybe it's emulator specific. Will recheck it and let you know.

**Comment by KevinSmall** [comment]
@Over17 I did some mores testing and got these results:
```
Unity      Android 6.0          Android 5.1.1        Android 4.4.2 API 19
Version    Nexus 4 Emulator     Samsung s5 mini      Nexus 5 Emulator   
5.5.0f3      BUBBLE               NO BUBBLE            BUBBLE      					        
5.3.4f1      BUBBLE               NO BUBBLE            BUBBLE
```
I believe it also shows a bubble on a physical device running 4.4.4, but I'm unable to check this myself.
The above results make it look like it is an Android OS version that is that cause, or perhaps an Emulator cause like you said (the only physical device I have is the Samsung and it shows no bubble).  My target devices are running 4.4.4 and I can't change that.

When you say that the IMMERSIVE flag is set on startup by Unity, is that in the splash screen part?  So if I were to disable splash screen entirely it might be ok?

**Comment by KevinSmall** [comment]
Hi @Over17 I have more information on this.

The fix of setting fullscreen = false as soon as the game loads has worked on the actual device running Android 4.4.4, so there is NO BUBBLE on the actual device with this fix.

Therefore we can close this issue, as although the problem exists still on my emulators, it does NOT occur on the actual device.  So perhaps it is just an Emulator thing like you said.

Thanks for looking into it.  (I'd still be interested to know why it happens and how to prevent it on the Emus but that is purely out of interest)

**Comment by Over17** [comment]
@KevinSmall thanks for getting back!
