### ISSUE TITLE
Error to compile

### ISSUE THREAD

**Issue by caiocabralbr** [Over17/UnityShowAndroidStatusBar#22]
Transform output file D:\caioc\Documents\Unity\libs\unity-classes.jar does not exist.

**Comment by Over17** [comment]
I understand you are trying to rebuild the plugin, correct? (you don't need it in basic scenarios)

The documentation says:

How to Build
    Put Unity's classes.jar into src/UnityShowAndroidStatusBar/libs/

So you'd have to find unity's classes.jar in your Editor installation, and put it into the path written above.
