### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by akari23** [Over17/UnityShowAndroidStatusBar#25]
![image](https://user-images.githubusercontent.com/33738081/112750195-5cb22080-8ff1-11eb-968e-5c4f3db4d022.png)
hi, im new with unity and android, can i know what happen with this?
i cant build when the "unityShowAndroidStatusBar.aar" is on my project sir :(

**Comment by Over17** [comment]
hi! looking into the console for the details, as mentioned in the messages, should help you. this is most likely something related to your setup.

**Comment by akari23** [comment]
![image](https://user-images.githubusercontent.com/33738081/112819637-fdb2e100-90ae-11eb-99e0-4a776801bcfb.png)
even im making empty project, i still got the same error
or am i do it wrong?
it just, copy the file "UnityShowAndroidStatusBar"
and take the plugin folder that containt the xml and .aar file,
and build
am i right?

**Comment by Over17** [comment]
The screenshot mentions duplicate classes, likely you've added the AAR twice, depending on which classes are duplicate.
There is even a link to android docs with troubleshooting.
Sorry, there is no more support I can offer you.
