### ISSUE TITLE
Hidden navigation bar

### ISSUE THREAD

**Issue by SamihElsakhawi** [Over17/UnityShowAndroidStatusBar#4]
Hello, and thanks for your plugin!

I would like to know if is it possible to hide the navigation bar, while show the status bar?

I tried a few things and it doesn't work :/

**Comment by Over17** [comment]
Hi!

If I remember correctly, on Android before 4.4 (KitKat) the "lights out" mode can be activated, while showing the reduced status bar. It happens so if you keep Screen.fullScreen to true.
It's not so easy on KitKat, I think. Probably not working - will double check when I'm back from vacation.

**Comment by SamihElsakhawi** [comment]
OK, thanks for the answer, i will wait ;)

**Comment by SamihElsakhawi** [comment]
Any news about my issue?

**Comment by Over17** [comment]
I think it is not possible to **hide** the navigation bar and show the status bar (at least, in a non-hacky way).

"Lights out" mode is just dimming the buttons in the navigation bar to dots. Nothing is really hidden, all the buttons are operational: https://developer.android.com/design/patterns/fullscreen.html
