### ISSUE TITLE
Changing color navigation bar

### ISSUE THREAD

**Issue by SamihElsakhawi** [Over17/UnityShowAndroidStatusBar#5]
Hey,

I would like to know if is it possible to change the color of the navigation bar?

**Comment by Over17** [comment]
Hi!

It is.

1. Use the non-transparent theme, Transparent navigation bar does not allow for the color change: https://developer.android.com/reference/android/view/Window.html#setNavigationBarColor(int)
2. in res/values-v21/styles.xml, modify the non-transparent theme as follows:
`<style name="UnityStatusBarTheme" parent="android:Theme.Material.Light.NoActionBar.Fullscreen">
<item name="android:navigationBarColor">your_color_here</item>
</style>`
3. Enjoy

Additional info: http://stackoverflow.com/questions/27839105/android-lollipop-change-navigation-bar-color

**Comment by SamihElsakhawi** [comment]
Thanks a lot! :)

But where i put my color, it's a color int or i can put my own RGB value?

**Comment by Over17** [comment]
Color can be RGB or a pre-defined name.
You should probably read up on Android docs: https://developer.android.com/guide/topics/ui/themes.html
