### ISSUE TITLE
Not work after upgrade to Unity 5.5/5.6

### ISSUE THREAD

**Issue by weilitao** [Over17/UnityShowAndroidStatusBar#6]
Hi,

I have found this plugin do not work with recent Unity version(5.5, 5.6). But It works when I use Unity 5.4.

**Comment by Over17** [comment]
Hi!

I would appreciate more details - what do you mean by "not working", what is the project setup, what is the device.
Are you using the latest (AAR) version?

**Comment by weilitao** [comment]
Hi, sorry for the bad description.

I am using the latest AAR version. Sometimes ago I use Unity 5.3/5.4, this plugin works OK. My game would not go into the immersive mode.

But when I update to Unity 5.6 (I have also tested with Unity 5.5), my game would go into the immersive mode, and the annoy dialog "viewing full screen. To exit, swipe down from the top" would appear.

After some research, I think the approach used by this plugin works well. The problem is: 
1. When start the game, it would not in immersive mode.
2. Then game continue going to the splash screen, immersive mode appear and the dialog open.
3. Finally go to the game logic, immersive mode go away and navigation bar would shown.

So maybe Unity has changed something on splash screen in 5.5, making the plugin not work.

And my test device is on 4.4 and 6.0 android tablet virtual devices and an android Set Top Box.

**Comment by Over17** [comment]
Virtual devices are pretty broken with regard to such fullscreen actions:
https://github.com/Over17/UnityShowAndroidStatusBar/issues/2

Could you try on a real device and see if you are still experiencing issues? I'm pretty sure it works for me on the latest 2017.1 version.

**Comment by weilitao** [comment]
Hi Over17,

I have tested on real device following your advice. 
1. Nexus 7 with Android 6.0.1.
    -- The immersive dialog don't show.
2. An android Box with Android 4.4.2
   -- The immersive dialog appear.

Then I downgrade my Unity to 5.4.5, then both Android virtual devices and the Android box wouldn't show the immersive box.

**Comment by Over17** [comment]
What is the android box? Where is the ROM coming from?

**Comment by weilitao** [comment]
It is a custom android box mode by cable TV network operators in China, I can not get more information about the ROM. Since I just need build game for that, so I must support this kind of device :(

**Comment by Over17** [comment]
I'm afraid I can't do anything with it. I will check how it works on a Android TV console and will get back.

**Comment by Over17** [comment]
No answer/follow-up - closing.
