### ISSUE TITLE
Huawei Y7, android 7.0 black screen on launch

### ISSUE THREAD

**Issue by gromilQaaaa** [Over17/UnityShowAndroidStatusBar#8]
![screenshot_20180116-225823 1](https://user-images.githubusercontent.com/5392680/35011990-cdf3c6be-fb10-11e7-9d63-580160f4cb5a.png)
Huawei Y7, android 7.0

Fullscreen = true, gives such result right after unity splash screen. If false - no problems, but no status bar

**Comment by gromilQaaaa** [comment]
btw in this code status bar works
https://forum.unity.com/threads/how-to-make-status-bar-visible-on-runtime-with-applications-built-by-unity.72959/

**Comment by Over17** [comment]
I don't have the phone in question at hand, but if you share your project and logcat of a development build - I'll try to check it out.

**Comment by Over17** [comment]
@gromilQaaaa any news?

> I don't have the phone in question at hand, but if you share your project and logcat of a development build - I'll try to check it out.

**Comment by Over17** [comment]
Based on the garbage most likely buffer not properly cleared.
No answer
