### ISSUE TITLE
Dont work in galaxy s8

### ISSUE THREAD

**Issue by union707** [Over17/UnityShowAndroidStatusBar#9]
the plugin dont work in galaxy s8, the immersive mode seems to be persistent and the plugin dont disable it (the bar appears and disappears)

im using unity 2017.3 and target sdk 23

**Comment by union707** [comment]
tested in unity 2017.1 too... really doesnt work in galaxy s8

**Comment by Over17** [comment]
Confirmed. Looks like non-fullscreen mode is broken in Unity.

**Comment by Over17** [comment]
Strike that - broken in 2018.1. Looking further.

**Comment by Over17** [comment]
I just tried S8 + Unity 2017.3.1p4 - works fine.

**Comment by Over17** [comment]
Everything I tried so far works for me. Most likely something is wrong with your manifest. Please make sure you use the Unity[Transparent]StatusBarTheme and com.unity3d.nostatusbar.UnityPlayerActivityStatusBar activity.

**Comment by union707** [comment]
unity revert back onwindowsfocuschanged(true) to immersive_stick in an internal thread that create a surface view.
it is impossible to prevent it because decorations are in inside this internal surface and it is added in a different thread so i can not prevent this

**Comment by union707** [comment]
well, my manifest is correct.

i tested in many simulators mobile sdks of android studio too and the bug is the same. 

unity 2017 (now o tested in unity 2017.1) change to immersive_stick the decoration of internal surface view.
in documentation of android the immersive_stick mode dont de call OnDecorationChanged so it is impossible to prevent it

**Comment by Over17** [comment]
I can't know if your manifest is correct if you don't share it with me.
The feature doesn't work with emulators, as far as I know.
As I said. I just checked it on a S8 and it worked like a charm. (Unity 2018.1 has issues but they are being fixed)

**Comment by Over17** [comment]
Please share your project, exact Unity version and the steps to reproduce.

**Comment by union707** [comment]
Sorry for the delay, it is just an empty project with your plugin

and a script with script below

include UnityEngine;

public class FullScreenTest : MonoBehaviour
{
void Start()
{
Screen.fullScreen = true;
}
}

as i said.. the error comes from functions onWindowFocusChanged in Android UnityPlayerActivity that instantiates a SurfaceView (i used AndroidStudio to debug) and this surface view contains decorator flag IMMERSIVE_STICK...

as this surface was added in mainwindows in different thread we cant change block it.

PS: Using Unity 2017.1.0, or unity 2017.3.1 PERSONAL EDITION (Unity Splash Page enabled)

**Comment by Over17** [comment]
I just checked again on S8 and it works. Your script should read Screen.fullScreen = false to show the status bar.
